services:
  cloudflared:
    container_name: cloudflared
    image: crazymax/cloudflared:latest
    command: proxy-dns
    environment:
      - TZ=${TZ:-America/Chicago}
      - TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query
      - TUNNEL_DNS_PORT=5053
      - TUNNEL_DNS_ADDRESS=0.0.0.0
    networks:
      pihole_network:
        aliases:
          - dns.cloudflared
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "${DNS_TCP_PORT:-5335}:53/tcp"
      - "${DNS_UDP_PORT:-5335}:53/udp"
      - "${WEB_PORT:-8080}:80/tcp"
    environment:
      TZ: ${TZ:-America/Chicago}
      WEBPASSWORD: ${WEBPASSWORD:-changeme}
      PIHOLE_DNS_: 'dns.cloudflared#5053'
      DNS_FQDN_REQUIRED: 'true'
    volumes:
      - './pihole-data/etc-pihole:/etc/pihole'
      - './pihole-data/etc-dnsmasq.d:/etc/dnsmasq.d'
    networks:
      - pihole_network
    depends_on:
      - cloudflared
    restart: unless-stopped

networks:
  pihole_network:
    name: pihole_network
